service: cost-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:eu-central-1:679625349984:table/Costs"
        - "arn:aws:dynamodb:eu-central-1:679625349984:table/Costs/index/UserId-index"
  environment:
    TABLE_NAME: Costs

functions:
  app:
    handler: src/index.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'